apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nooooo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nooooo 
  name: nooooo
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nooooo
    weight: 100 
