apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nooooo-gitops
  description: This is GitOps manifest for nooooo   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nooooo
    backstage.io/kubernetes-id: nooooo 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: nooooo   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nooooo
